GET http://localhost:9080/jakarta-soap-service/HelloWorldService?wsdl

###

POST http://localhost:9080/jakarta-soap-service/HelloWorldService
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="ninckblokje/HelloWorld">
    <soap:Body>
        <tns:helloWorld>
            <name>IntelliJ</name>
        </tns:helloWorld>
    </soap:Body>
</soap:Envelope>
