<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  ~ Copyright (c) 2021, ninckblokje
  ~ All rights reserved.
  ~
  ~ Redistribution and use in source and binary forms, with or without
  ~ modification, are permitted provided that the following conditions are met:
  ~
  ~ * Redistributions of source code must retain the above copyright notice, this
  ~   list of conditions and the following disclaimer.
  ~
  ~ * Redistributions in binary form must reproduce the above copyright notice,
  ~   this list of conditions and the following disclaimer in the documentation
  ~   and/or other materials provided with the distribution.
  ~
  ~ THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  ~ AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  ~ IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  ~ DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  ~ FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  ~ DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  ~ SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  ~ CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  ~ OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  ~ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  -->
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="ninckblokje/PingPongService"
	xmlns:pp="ninckblokje/PingPong"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="PingPongService"
	targetNamespace="ninckblokje/PingPongService">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="ninckblokje/PingPong" schemaLocation="PingPong.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="PingRequest">
		<wsdl:part element="pp:PingRequest" name="parameters" />
	</wsdl:message>
	<wsdl:message name="PongResponse">
		<wsdl:part element="pp:PongResponse" name="parameters" />
	</wsdl:message>
	<wsdl:portType name="PingPongService">
		<wsdl:operation name="Ping">
			<wsdl:input message="tns:PingRequest" />
			<wsdl:output message="tns:PongResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="PingPongServiceSOAP" type="tns:PingPongService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="Ping">
			<soap:operation soapAction="ninckblokje/PingPongService/Ping" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PingPongService">
		<wsdl:port binding="tns:PingPongServiceSOAP" name="PingPongServiceSOAP">
			<soap:address location="http://localhost:9080"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
