GET http://localhost:8080/cxf/PingPongService?wsdl

###

POST http://localhost:8080/cxf/PingPongService
Content-Type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pp="ninckblokje/PingPong">
    <soap:Body>
        <pp:PingRequest/>
    </soap:Body>
</soap:Envelope>
